/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class com_veclink_media_CodecTest */

#ifndef _Included_com_veclink_media_CodecTest
#define _Included_com_veclink_media_CodecTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_veclink_media_CodecTest
 * Method:    testCodec
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_veclink_media_CodecTest_testCodec
  //(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
